// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Clsx from "clsx";
import * as Nanoid from "nanoid";
import * as TailwindMerge from "tailwind-merge";

var Clsx$1 = {};

var Nanoid$1 = {};

var TailwindMerge$1 = {};

function cn(inputs) {
  return TailwindMerge.twMerge(inputs.map(function (prim) {
                  return Clsx.clsx(prim);
                }));
}

var nanoid = Nanoid.customAlphabet("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", 9);

var Metadata = {};

export {
  Clsx$1 as Clsx,
  Nanoid$1 as Nanoid,
  TailwindMerge$1 as TailwindMerge,
  cn ,
  nanoid ,
  Metadata ,
}
/* nanoid Not a pure module */
