// Generated by ReScript, PLEASE EDIT WITH CARE
'use client'

import * as MaxWidthWrapper from "../../../../../../components/MaxWidthWrapper.bs.mjs";
import * as ReactHookForm from "react-hook-form";
import * as JsxRuntime from "react/jsx-runtime";

function CoupleInformationForm(props) {
  var form = ReactHookForm.useForm({
        defaultValues: {
          event_name: "",
          description: undefined,
          is_show_groom_name_first: false,
          groom_name: "",
          bride_name: "",
          website_url: ""
        }
      });
  var formState = form.formState;
  var isValid = formState.isValid;
  console.log(isValid);
  return JsxRuntime.jsx(MaxWidthWrapper.make, {
              children: "hello"
            });
}

var make = CoupleInformationForm;

export {
  make ,
}
/* MaxWidthWrapper Not a pure module */
