// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as ReactHookForm from "../../../bindings/ReactHookForm.bs.mjs";

var Formm = ReactHookForm.Make({});

var config = ReactHookForm.Rules.make({
      required: true,
      maxLength: 10,
      minLength: 3
    });

var Id = Curry._1(Formm.MakeInput, {
      name: "id",
      config: config
    });

export {
  Formm ,
  Id ,
}
/* Formm Not a pure module */
