// Generated by ReScript, PLEASE EDIT WITH CARE
'use client'

import * as Card from "../../../../../../components/ui/card/Card.bs.mjs";
import * as Tabs from "../../../../../../components/ui/tabs/Tabs.bs.mjs";
import * as React from "react";
import Link from "next/link";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MaxWidthWrapper from "../../../../../../components/MaxWidthWrapper.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactTabs from "@radix-ui/react-tabs";
import * as ReactIcons from "@radix-ui/react-icons";

function OverviewPage$default(props) {
  return JsxRuntime.jsx(MaxWidthWrapper.make, {
              children: JsxRuntime.jsx("section", {
                    children: JsxRuntime.jsx(React.Suspense, {
                          children: Caml_option.some(JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("h1", {
                                            children: "Dashboard",
                                            className: "font-display text-4xl"
                                          }),
                                      JsxRuntime.jsx(Link, {
                                            href: "false_",
                                            locale: "false_",
                                            children: "Hello"
                                          }),
                                      JsxRuntime.jsxs(ReactTabs.Root, {
                                            defaultValue: "overview",
                                            className: "space-y-4",
                                            children: [
                                              JsxRuntime.jsxs(Tabs.List.make, {
                                                    children: [
                                                      JsxRuntime.jsx(Tabs.Trigger.make, {
                                                            value: "overview",
                                                            children: "Overview"
                                                          }),
                                                      JsxRuntime.jsx(Tabs.Trigger.make, {
                                                            value: "guest_list",
                                                            children: "Guest List"
                                                          }),
                                                      JsxRuntime.jsx(Tabs.Trigger.make, {
                                                            value: "other",
                                                            children: "Other"
                                                          })
                                                    ]
                                                  }),
                                              JsxRuntime.jsx(Tabs.Content.make, {
                                                    children: JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsxs(Card.Card.make, {
                                                                  children: [
                                                                    JsxRuntime.jsxs(Card.Header.make, {
                                                                          children: [
                                                                            JsxRuntime.jsx(Card.Title.make, {
                                                                                  children: "Total Guests"
                                                                                }),
                                                                            JsxRuntime.jsx(ReactIcons.PersonIcon, {})
                                                                          ],
                                                                          className: "flex flex-row items-center justify-between space-y-0 pb-2"
                                                                        }),
                                                                    JsxRuntime.jsx(Card.Content.make, {
                                                                          children: JsxRuntime.jsx("div", {
                                                                                children: "219",
                                                                                className: "text-2xl font-bold"
                                                                              })
                                                                        })
                                                                  ],
                                                                  className: "w-full"
                                                                }),
                                                            JsxRuntime.jsxs(Card.Card.make, {
                                                                  children: [
                                                                    JsxRuntime.jsxs(Card.Header.make, {
                                                                          children: [
                                                                            JsxRuntime.jsx(Card.Title.make, {
                                                                                  children: "Total Guests"
                                                                                }),
                                                                            JsxRuntime.jsx(ReactIcons.PersonIcon, {})
                                                                          ],
                                                                          className: "flex flex-row items-center justify-between space-y-0 pb-2"
                                                                        }),
                                                                    JsxRuntime.jsx(Card.Content.make, {
                                                                          children: JsxRuntime.jsx("div", {
                                                                                children: "146",
                                                                                className: "text-2xl font-bold"
                                                                              })
                                                                        })
                                                                  ],
                                                                  className: "w-full"
                                                                }),
                                                            JsxRuntime.jsxs(Card.Card.make, {
                                                                  children: [
                                                                    JsxRuntime.jsxs(Card.Header.make, {
                                                                          children: [
                                                                            JsxRuntime.jsx(Card.Title.make, {
                                                                                  children: "Total Guests"
                                                                                }),
                                                                            JsxRuntime.jsx(ReactIcons.PersonIcon, {})
                                                                          ],
                                                                          className: "flex flex-row items-center justify-between space-y-0 pb-2"
                                                                        }),
                                                                    JsxRuntime.jsx(Card.Content.make, {
                                                                          children: JsxRuntime.jsx("div", {
                                                                                children: "421",
                                                                                className: "text-2xl font-bold"
                                                                              })
                                                                        })
                                                                  ],
                                                                  className: "w-full"
                                                                })
                                                          ],
                                                          className: "grid gap-4 md:grid-cols-2 lg:grid-cols-3"
                                                        }),
                                                    value: "overview"
                                                  }),
                                              JsxRuntime.jsx(Tabs.Content.make, {
                                                    children: JsxRuntime.jsx("div", {
                                                          children: JsxRuntime.jsxs(Card.Card.make, {
                                                                children: [
                                                                  JsxRuntime.jsxs(Card.Header.make, {
                                                                        children: [
                                                                          JsxRuntime.jsx(Card.Title.make, {
                                                                                children: "Total Guests"
                                                                              }),
                                                                          JsxRuntime.jsx(ReactIcons.PersonIcon, {})
                                                                        ],
                                                                        className: "flex flex-row items-center justify-between space-y-0 pb-2"
                                                                      }),
                                                                  JsxRuntime.jsx(Card.Content.make, {
                                                                        children: JsxRuntime.jsx("div", {
                                                                              children: "219",
                                                                              className: "text-2xl font-bold"
                                                                            })
                                                                      })
                                                                ],
                                                                className: "w-full"
                                                              }),
                                                          className: "grid gap-4 md:grid-cols-2 lg:grid-cols-3"
                                                        }),
                                                    value: "guest_list"
                                                  }),
                                              JsxRuntime.jsx(Tabs.Content.make, {
                                                    children: JsxRuntime.jsx("div", {
                                                          children: JsxRuntime.jsxs(Card.Card.make, {
                                                                children: [
                                                                  JsxRuntime.jsxs(Card.Header.make, {
                                                                        children: [
                                                                          JsxRuntime.jsx(Card.Title.make, {
                                                                                children: "Total Guests"
                                                                              }),
                                                                          JsxRuntime.jsx(ReactIcons.PersonIcon, {})
                                                                        ],
                                                                        className: "flex flex-row items-center justify-between space-y-0 pb-2"
                                                                      }),
                                                                  JsxRuntime.jsx(Card.Content.make, {
                                                                        children: JsxRuntime.jsx("div", {
                                                                              children: "219",
                                                                              className: "text-2xl font-bold"
                                                                            })
                                                                      })
                                                                ],
                                                                className: "w-full"
                                                              }),
                                                          className: "grid gap-4 md:grid-cols-2 lg:grid-cols-3"
                                                        }),
                                                    value: "other"
                                                  })
                                            ]
                                          })
                                    ],
                                    className: "space-y-6"
                                  })),
                          fallback: Caml_option.some(JsxRuntime.jsx("div", {
                                    children: "Loading..."
                                  }))
                        }),
                    className: "pt-10"
                  })
            });
}

var $$default = OverviewPage$default;

export {
  $$default ,
  $$default as default,
}
/* Card Not a pure module */
