// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as ReactHookForm from "../../../../../../bindings/ReactHookForm.bs.mjs";

var Form = ReactHookForm.Make({});

var config = ReactHookForm.Rules.make({
      required: true,
      minLength: 3
    });

var EventName = Curry._1(Form.MakeInput, {
      name: "event_name",
      config: config
    });

var FormInput = {
  EventName: EventName
};

export {
  Form ,
  FormInput ,
}
/* Form Not a pure module */
