// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../../../lib/Utils.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Card$Card(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: Utils.cn([
                    "rounded-xl border bg-card text-card-foreground shadow",
                    cn
                  ])
            });
}

var Card = {
  make: Card$Card
};

function Card$Header(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: Utils.cn([
                    "flex flex-col space-y-1.5 p-6",
                    cn
                  ])
            });
}

var Header = {
  make: Card$Header
};

function Card$Title(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx("h1", {
              children: props.children,
              className: Utils.cn([
                    "font-semibold leading-none tracking-tight",
                    cn
                  ])
            });
}

var Title = {
  make: Card$Title
};

function Card$Description(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: Utils.cn([
                    "text-sm text-muted-foreground",
                    cn
                  ])
            });
}

var Description = {
  make: Card$Description
};

function Card$Content(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: Utils.cn([
                    "p-6 pt-0",
                    cn
                  ])
            });
}

var Content = {
  make: Card$Content
};

function Card$Footer(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: Utils.cn([
                    "flex items-center p-6 pt-0",
                    cn
                  ])
            });
}

var Footer = {
  make: Card$Footer
};

export {
  Card ,
  Header ,
  Title ,
  Description ,
  Content ,
  Footer ,
}
/* Utils Not a pure module */
