name: Code Check

run-name: ${{ github.actor }} is testing out Code Check 🚀

on:
  push:
    branches: [main, next]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out repository code 📥
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js 📦
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          run_install: false
      - name: Get pnpm store directory 📦
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache 📦
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # - name: Install bun 📦
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: "latest"

      - name: Install dependencies 📦
        run: pnpm install

      - name: Lint 🧹
        run: pnpm run lint

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Check out repository code 📥
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js 📦
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory 📦
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache 📦
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # - name: Install bun 📦
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: "latest"

      - name: Install dependencies 📦
        run: pnpm install

      - name: Format 🧹
        run: pnpm run format:check
