// Generated by ReScript, PLEASE EDIT WITH CARE
'use client'

import * as Utils from "../../../lib/Utils.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactTabs from "@radix-ui/react-tabs";

function Tabs$List(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx(ReactTabs.List, {
              className: Utils.cn([
                    "inline-flex h-9 items-center justify-center rounded-lg bg-muted p-1 text-muted-foreground",
                    cn
                  ]),
              children: props.children
            });
}

var List = {
  make: Tabs$List
};

function Tabs$Trigger(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx(ReactTabs.Trigger, {
              className: Utils.cn([
                    "inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow",
                    cn
                  ]),
              value: props.value,
              children: props.children
            });
}

var Trigger = {
  make: Tabs$Trigger
};

function Tabs$Content(props) {
  var className = props.className;
  var cn = className !== undefined ? className : "";
  return JsxRuntime.jsx(ReactTabs.Content, {
              className: Utils.cn([
                    "mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
                    cn
                  ]),
              value: props.value,
              children: props.children
            });
}

var Content = {
  make: Tabs$Content
};

var Root;

export {
  Root ,
  List ,
  Trigger ,
  Content ,
}
/* Utils Not a pure module */
