// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../../../lib/Utils.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactTabs from "@radix-ui/react-tabs";

var Internal = {};

function Tabs__Trigger(props) {
  return JsxRuntime.jsx(ReactTabs.Trigger, {
              className: Utils.cn([
                    "inline-flex items-center justify-center whitespace-nowrap rounded-md px-3 py-1 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow",
                    Core__Option.getWithDefault(props.className, "")
                  ]),
              value: props.value,
              children: props.children
            });
}

var make = Tabs__Trigger;

export {
  Internal ,
  make ,
}
/* Utils Not a pure module */
