// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../../../lib/Utils.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactTabs from "@radix-ui/react-tabs";

var Internal = {};

function Tabs__List(props) {
  return JsxRuntime.jsx(ReactTabs.List, {
              className: Utils.cn([
                    "inline-flex h-9 items-center justify-center rounded-lg bg-muted p-1 text-muted-foreground",
                    Core__Option.getWithDefault(props.className, "")
                  ]),
              children: props.children
            });
}

var make = Tabs__List;

export {
  Internal ,
  make ,
}
/* Utils Not a pure module */
